---
all:
  children:
# Server infrastructure 
    service_auth_servers:
      hosts:
        auth1:
          ansible_host: 10.51.21.181
        auth2:
          ansible_host: 10.51.21.182
    service_storage_servers:
      hosts:
        pcm1:
          ansible_host: 10.51.21.183
        pcm2:
          ansible_host: 10.51.21.184
        pcm3:
          ansible_host: 10.51.21.185
# Client infrastructure          
    client_workstations:
      hosts:
        ws1:
          ansible_host: 10.51.21.186
# Variables for inventory
  vars:
    default_dns_server: "8.8.8.8"
    main_dns_server: "10.51.21.181"
    second_dns_server: "10.51.21.182"
    network_addr: "10.51.21.0"
    network_cidr: "24"
    hypervisor_node_addr: "10.51.21.254"
    hypervisor_node_name: "m11266"
    pcm1_vm_nodeid: "183"
    pcm2_vm_nodeid: "184"
    pcm3_vm_nodeid: "185"
...