---
- meta: end_play
  when: (ansible_distribution != "CentOS" and ansible_distribution_major_version != "7")

- name: Install required packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - dbus
    - NetworkManager-glib
    - NetworkManager
    - tcpdump
  notify: "restart NetworkManager"

- name: Change DNS
  nmcli:
    conn_name: "{{ primary_interface }}"
    type: ethernet
    dns4:
    - "8.8.8.8"
    state: present
  notify: "restart NetworkManager"

- meta: flush_handlers
...