---
all:
  children:
# Server infrastructure 
    service_auth_servers:
      hosts:
        auth1:
          ansible_host: 192.168.69.206
          prod_ip_addr: "192.168.69.206"
        auth2:
          ansible_host: 192.168.69.205
          prod_ip_addr: "192.168.69.205"
    service_storage_servers:
      hosts:
        pcm1:
          ansible_host: 192.168.69.204
          prod_ip_addr: "192.168.69.204"
        pcm2:
          ansible_host: 192.168.69.203
          prod_ip_addr: "192.168.69.203"
        pcm3:
          ansible_host: 192.168.69.202
          prod_ip_addr: "192.168.69.202"
      vars:
        cluster_virtual_ip: "10.51.21.187"
        drbd_node1_ip: "10.51.21.183"
        drbd_node2_ip: "10.51.21.184"
        drbd_node3_ip: "10.51.21.185"  
# Client infrastructure          
    client_workstations:
      hosts:
        ws1:
          ansible_host: 192.168.69.201
          prod_ip_addr: "192.168.69.201"
  vars:
    default_dns_server: "192.168.69.254"
    main_dns_server: "192.168.69.206"
    second_dns_server: "192.168.69.205"
    network_addr: "192.168.69.0"
    network_cidr: "24"
...